#     _____ __        ________      __  ____  _ ___ __  _
#    / ___// /_____ _/ __/ __/     / / / / /_(_) (_) /_(_)__  _____
#    \__ \/ __/ __ `/ /_/ /_______/ / / / __/ / / / __/ / _ \/ ___/
#   ___/ / /_/ /_/ / __/ __/_____/ /_/ / /_/ / / / /_/ /  __(__  )
#  /____/\__/\__,_/_/ /_/        \____/\__/_/_/_/\__/_/\___/____/
#

#DON'T TOUCH THIS
version: 1.0


#check for update of the plugin (auto update)
check-update: true #default (true)

#show a message when a player join the server
join-message: true #default (true)

#
start-event:
  enabled: true #default (true)