name: StaffUtilities
version: 1.0
authors: [CraftTechPlugin]
main: it.crafttechplugin.staffutilities.Main
depend:  [Vault]
softdepend:
  - LuckPerms
loadbefore: [DeluxeHub]
commands:
  gmc:
  fly:
  pl:
  plugins:
  startevent:
  vanish:
    aliases: ["v"]
  staffutilities:
    aliases: ["su"]
  tp:
  tphere:
  tpall:
  enderchest:
    aliases: ["ec"]
  invsee:
  creload:
  ban:
  unban:
  mute:
  unmute:
  bansystem:
  msg:
  freeze:
  staffvanish:
    aliases:
      - sv
  spy:
  staffmode:
    aliases:
      - sm
  randomplayertp: