name: StaffUtilities
version: 1.4
authors: [ImReddo_, FrancyFily]
main: it.gramdeveloment.staffutilities.Main
depend:  [PlaceHolderAPI, Vault, LuckPerms]
loadbefore: [DeluxeHub]
commands:
  gmc:
  credits:
  fly:
  pl:
  plugins:
  startevent:
  vanish:
    aliases: ["v"]
  staffutilities:
  tp:
  tphere:
  tpall:
  enderchest:
    aliases: ["ec"]
  invsee: